name: num-converter CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install pip
        run: |
          pip install --no-cache-dir --upgrade pip


      - name: Install dependencies
        run: |
          pip install fastapi uvicorn python-multipart pytest jinja2
          pip3 install httpx

      - name: Run tests
        run: |
          python3 -m pytest tests/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets. DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and tag Docker image
        run: |
          docker build -t numbersystem-converter .
          docker tag numbersystem-converter:latest ${{ secrets.DOCKERHUB_USERNAME }}/numbersystem-converter:latest

      - name: Push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/numbersystem-converter:latest

